name: causal-inference-toolkit
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas=2.1.4
  - numpy=1.24.3
  - scipy=1.11.4
  - scikit-learn=1.3.2
  - matplotlib=3.8.2
  - seaborn=0.13.0
  - plotly=5.17.0
  - networkx=3.2.1
  - jupyter=1.0.0
  - ipykernel=6.27.1
  - notebook=7.0.6
  - statsmodels=0.14.1
  - pytest=7.4.3
  - tqdm=4.66.1
  - joblib=1.3.2
  - pyyaml=6.0.1
  - pip
  - pip:
    - dowhy==0.11
    - econml==0.15.0
    - causalml==0.15.0
    - streamlit==1.29.0
    - pingouin==0.5.3
    - pytest-cov==4.1.0
    - graphviz==0.20.1
    - bokeh==3.3.2
    - altair==5.2.0
    - black==23.11.0
    - flake8==6.1.0
    - isort==5.12.0 